language: objective-c
osx_image: xcode7.2
cache: cocoapods

before_install:
  - brew install swiftlint
  - gem install xcpretty
  - gem install cocoapods

install:
  - pod install

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace KataSuperHeroes.xcworkspace -scheme 'KataSuperHeroes' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
